title: ASR假设选择
type: community
group: Ranking & Scoring
image: /static/templates/asr-hypotheses.png
details: <h1>Choose the most accurate Automatic Speach Recognition (ASR) hypothese</h1>
config: |
  <View>
    <Audio name="audio" value="$audio"/>
    <Choices name="transcriptions" toName="audio" value="$transcriptions" selection="highlight"/>
    <Style>
      .lsf-choice__item {
        padding: var(--spacing-tighter) var(--spacing-tight);
        box-shadow: 0 2px 4px rgba(var(--color-neutral-shadow-raw) / calc(16% * var(--shadow-intensity))) ;
        background-color: var(--color-neutral-background);
        border-radius: var(--corner-radius-small);
        margin: 0 var(--spacing-tighter) var(--spacing-tighter) var(--spacing-tighter);
        line-height: 1.6rem;
        transition: all 150ms ease-out;
      }
      
      .lsf-choice__item:hover {
        background-color: var(--color-primary-emphasis-subtle);
      }
    </Style>
  </View>
  <!-- { "data": {
    "audio": "https://htx-pub.s3.amazonaws.com/datasets/audio/f2btrop6.0.wav",
    "transcriptions": [{
      "value": "Potrostith指出，如果建立校内诊所，学生接受所提供的每项服务都需要获得家长的许可"
    }, {
      "value": "Potrostith指出，如果建立校内诊所，学生接受所提供的每项服务都需要获得家长的许可"
    }, {
      "value": "Purporting指出，如果建立校内诊所，学生接受所提供的每项服务都需要获得家长的许可。"
    }, {
      "value": "Pork指出，如果建立学校诊所，学生接受所提供的每项服务都需要获得家长的许可。"
    }, {
      "value": "该目的指出，如果建立校内诊所，学生接受所提供的每项服务都需要获得家长的许可。"
    }]
  }} -->
