title: 视觉基因组
type: community
group: Computer Vision
image: /static/templates/visual-genome.png
details: |
  <h1>Label different described features</h1>
  <dl>
    <dt>Industry Applications</dt>
    <dd>scene understanding, visual reasoning, computer vision research, multimodal AI, robotics training, autonomous systems, visual question answering, image captioning, visual relationship detection, scene graph generation, complex scene analysis</dd>
    <dt>Associated Models</dt>
    <dd>region detection, attribute classification, relationship extraction, structured scene representation</dd>
    <dt>Domain Terminology</dt>
    <dd>scene graphs, visual knowledge, spatial relationships, object interactions, contextual understanding</dd>
  </dl>
config: |
  <View>
    <View style="display: flex; flex-wrap: wrap;">
      <View className="label-column">
        <Header value="区域"/>
        <RectangleLabels name="regions" toName="image" value="$regions"/>
    </View>
      <View className="label-column">
        <Header value="属性"/>
      <RectangleLabels name="attributes" toName="image" value="$attributes"/>
      </View>
      <View className="label-column">
        <Header value="关系"/>
      <RectangleLabels name="relationships" toName="image" value="$relationships"/>
      </View>
   
    </View>
    <Image name="image" value="$image"/>
    <Style>
    .label-column .lsf-labels {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
    }
    </Style>
  </View>
  <!-- { "data": {
    "image": "https://htx-pub.s3.amazonaws.com/templates/visual-genome/panda.jpeg",
    "regions": [{
      "value": "熊猫爪子里拿着东西"
    }, {
      "value": "熊猫背后的树木模糊不清"
    }, {
        "value": "熊猫爪中的竹子"
      }, {
        "value": "熊猫旁边的竹子"
      }, {
        "value": "熊猫很可爱"
      }],
    "attributes": [{
      "value": "标记是黑色的"
    }, {
      "value": "鼻子是黑色的"
    }, {
      "value": "脸是圆的"
    }, {
        "value": "木头是圆的"
      }],
    "relationships": [{
      "value": "孔洞开启日志"
    }, {
      "value": "树在熊后面"
    }, {
        "value": "熊猫的嘴"
      }]
  }}-->
